version: '3.8'

services:
  web:
    build: . 
    ports:
      - 2300:2300
    volumes:
      - .:/app:cached
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: postgres:13.3-alpine
    volumes:
      - hanami_data:/var/lib/postgres/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  hanami_data: 
